spring:
  application:
    name: microservice-sowings
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://servidorbasedatosmicroservicios.database.windows.net:1433;database=sowingsbd;user=microservicios;password=123q321Q@;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: com.chaquitaclla.microservice.products.shared.infrastructure.persistence.jpa.configuration.strategy.SnakeCaseNameStrat
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
    database: sql_server
    database-platform: org.hibernate.dialect.SQLServerDialect
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8083